name: Deploy to Azure

on:
  push:
    branches:
      - non-existing-branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Setup project
      working-directory: ./DummyDeploy/dummy-project
      run: |
        echo '{
          "name": "hello-world-app",
          "version": "1.0.0",
          "main": "index.js",
          "scripts": {
            "start": "node index.js"
          },
          "dependencies": {
            "express": "^4.18.2"
          }
        }' > package.json

    - name: Install dependencies
      working-directory: ./DummyDeploy/dummy-project
      run: npm install

    - name: Zip artifact for deployment
      working-directory: ./DummyDeploy/dummy-project
      run: zip -r release.zip ./*

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'as-mayday'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./DummyDeploy/dummy-project/release.zip